# GitHub Action for generating a contribution graph with a snake eating your contributions
name: Generate Snake

# Run this action on a schedule (every 12 hours) and also on manual trigger
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

# The job that will be run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v3

      # Generate the snake animation
      - uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: ${{ github.repository_owner }}

          # A list of SVG output files with the snake animation
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Push the generated files back to the repository
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
